#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.OrderMGT.BL.DBModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KPOrder")]
	public partial class OrderDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertconfig_connection(config_connection instance);
    partial void Updateconfig_connection(config_connection instance);
    partial void Deleteconfig_connection(config_connection instance);
    partial void Insertorder_log_interface(order_log_interface instance);
    partial void Updateorder_log_interface(order_log_interface instance);
    partial void Deleteorder_log_interface(order_log_interface instance);
    partial void Insertorder_session(order_session instance);
    partial void Updateorder_session(order_session instance);
    partial void Deleteorder_session(order_session instance);
    partial void Insertorder_transaction(order_transaction instance);
    partial void Updateorder_transaction(order_transaction instance);
    partial void Deleteorder_transaction(order_transaction instance);
    partial void Insertorder_detail(order_detail instance);
    partial void Updateorder_detail(order_detail instance);
    partial void Deleteorder_detail(order_detail instance);
    partial void Insertorder_discount(order_discount instance);
    partial void Updateorder_discount(order_discount instance);
    partial void Deleteorder_discount(order_discount instance);
    partial void Insertorder_header(order_header instance);
    partial void Updateorder_header(order_header instance);
    partial void Deleteorder_header(order_header instance);
    partial void Insertorder_payment(order_payment instance);
    partial void Updateorder_payment(order_payment instance);
    partial void Deleteorder_payment(order_payment instance);
    #endregion
		
		public OrderDataClassesDataContext() : 
				base(global::KP.OrderMGT.BL.Properties.Settings.Default.KPOrderConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<df_flight> df_flights
		{
			get
			{
				return this.GetTable<df_flight>();
			}
		}
		
		public System.Data.Linq.Table<config_connection> config_connections
		{
			get
			{
				return this.GetTable<config_connection>();
			}
		}
		
		public System.Data.Linq.Table<df_airline> df_airlines
		{
			get
			{
				return this.GetTable<df_airline>();
			}
		}
		
		public System.Data.Linq.Table<df_airport> df_airports
		{
			get
			{
				return this.GetTable<df_airport>();
			}
		}
		
		public System.Data.Linq.Table<order_log_interface> order_log_interfaces
		{
			get
			{
				return this.GetTable<order_log_interface>();
			}
		}
		
		public System.Data.Linq.Table<order_session> order_sessions
		{
			get
			{
				return this.GetTable<order_session>();
			}
		}
		
		public System.Data.Linq.Table<order_transaction> order_transactions
		{
			get
			{
				return this.GetTable<order_transaction>();
			}
		}
		
		public System.Data.Linq.Table<order_detail> order_details
		{
			get
			{
				return this.GetTable<order_detail>();
			}
		}
		
		public System.Data.Linq.Table<order_discount> order_discounts
		{
			get
			{
				return this.GetTable<order_discount>();
			}
		}
		
		public System.Data.Linq.Table<order_header> order_headers
		{
			get
			{
				return this.GetTable<order_header>();
			}
		}
		
		public System.Data.Linq.Table<order_payment> order_payments
		{
			get
			{
				return this.GetTable<order_payment>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.df_flight")]
	public partial class df_flight
	{
		
		private string _flight_code;
		
		private char _del_flag;
		
		private string _flight_desc;
		
		private string _dest_airport_code;
		
		private string _arrdep_airport_code;
		
		private string _arrdep_terminal;
		
		private bool _d2;
		
		private bool _d3;
		
		private bool _d4;
		
		private bool _d5;
		
		private bool _d6;
		
		private bool _d7;
		
		private bool _d1;
		
		private string _arrdep_time;
		
		private bool _open_flight;
		
		private string _remark;
		
		private System.DateTime _add_datetime;
		
		private System.DateTime _update_datetime;
		
		private string _user_add;
		
		private string _user_update;
		
		private System.Data.Linq.Binary _time_stamp;
		
		private int _CutOffTime;
		
		private string _pickup_code;
		
		public df_flight()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_code", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string flight_code
		{
			get
			{
				return this._flight_code;
			}
			set
			{
				if ((this._flight_code != value))
				{
					this._flight_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_del_flag", DbType="Char(1) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public char del_flag
		{
			get
			{
				return this._del_flag;
			}
			set
			{
				if ((this._del_flag != value))
				{
					this._del_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_desc", DbType="Char(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string flight_desc
		{
			get
			{
				return this._flight_desc;
			}
			set
			{
				if ((this._flight_desc != value))
				{
					this._flight_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dest_airport_code", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string dest_airport_code
		{
			get
			{
				return this._dest_airport_code;
			}
			set
			{
				if ((this._dest_airport_code != value))
				{
					this._dest_airport_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrdep_airport_code", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string arrdep_airport_code
		{
			get
			{
				return this._arrdep_airport_code;
			}
			set
			{
				if ((this._arrdep_airport_code != value))
				{
					this._arrdep_airport_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrdep_terminal", DbType="Char(5)", UpdateCheck=UpdateCheck.Never)]
		public string arrdep_terminal
		{
			get
			{
				return this._arrdep_terminal;
			}
			set
			{
				if ((this._arrdep_terminal != value))
				{
					this._arrdep_terminal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d2", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d2
		{
			get
			{
				return this._d2;
			}
			set
			{
				if ((this._d2 != value))
				{
					this._d2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d3", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d3
		{
			get
			{
				return this._d3;
			}
			set
			{
				if ((this._d3 != value))
				{
					this._d3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d4", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d4
		{
			get
			{
				return this._d4;
			}
			set
			{
				if ((this._d4 != value))
				{
					this._d4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d5", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d5
		{
			get
			{
				return this._d5;
			}
			set
			{
				if ((this._d5 != value))
				{
					this._d5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d6", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d6
		{
			get
			{
				return this._d6;
			}
			set
			{
				if ((this._d6 != value))
				{
					this._d6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d7", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d7
		{
			get
			{
				return this._d7;
			}
			set
			{
				if ((this._d7 != value))
				{
					this._d7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d1", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d1
		{
			get
			{
				return this._d1;
			}
			set
			{
				if ((this._d1 != value))
				{
					this._d1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrdep_time", DbType="Char(5) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string arrdep_time
		{
			get
			{
				return this._arrdep_time;
			}
			set
			{
				if ((this._arrdep_time != value))
				{
					this._arrdep_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_open_flight", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool open_flight
		{
			get
			{
				return this._open_flight;
			}
			set
			{
				if ((this._open_flight != value))
				{
					this._open_flight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_datetime", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime add_datetime
		{
			get
			{
				return this._add_datetime;
			}
			set
			{
				if ((this._add_datetime != value))
				{
					this._add_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_datetime", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime update_datetime
		{
			get
			{
				return this._update_datetime;
			}
			set
			{
				if ((this._update_datetime != value))
				{
					this._update_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_add", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string user_add
		{
			get
			{
				return this._user_add;
			}
			set
			{
				if ((this._user_add != value))
				{
					this._user_add = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_update", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string user_update
		{
			get
			{
				return this._user_update;
			}
			set
			{
				if ((this._user_update != value))
				{
					this._user_update = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_stamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary time_stamp
		{
			get
			{
				return this._time_stamp;
			}
			set
			{
				if ((this._time_stamp != value))
				{
					this._time_stamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CutOffTime", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CutOffTime
		{
			get
			{
				return this._CutOffTime;
			}
			set
			{
				if ((this._CutOffTime != value))
				{
					this._CutOffTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pickup_code", DbType="Char(10)", UpdateCheck=UpdateCheck.Never)]
		public string pickup_code
		{
			get
			{
				return this._pickup_code;
			}
			set
			{
				if ((this._pickup_code != value))
				{
					this._pickup_code = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.config_connection")]
	public partial class config_connection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cn_code;
		
		private string _cn_name;
		
		private string _cn_server;
		
		private string _cn_database;
		
		private string _cn_uid;
		
		private string _cn_pwd;
		
		private string _cn_branch_no;
		
		private string _user_add;
		
		private string _user_update;
		
		private System.DateTime _add_datetime;
		
		private System.DateTime _update_datetime;
		
		private string _remark;
		
		private System.Data.Linq.Binary _time_stamp;
		
		private char _del_flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncn_codeChanging(string value);
    partial void Oncn_codeChanged();
    partial void Oncn_nameChanging(string value);
    partial void Oncn_nameChanged();
    partial void Oncn_serverChanging(string value);
    partial void Oncn_serverChanged();
    partial void Oncn_databaseChanging(string value);
    partial void Oncn_databaseChanged();
    partial void Oncn_uidChanging(string value);
    partial void Oncn_uidChanged();
    partial void Oncn_pwdChanging(string value);
    partial void Oncn_pwdChanged();
    partial void Oncn_branch_noChanging(string value);
    partial void Oncn_branch_noChanged();
    partial void Onuser_addChanging(string value);
    partial void Onuser_addChanged();
    partial void Onuser_updateChanging(string value);
    partial void Onuser_updateChanged();
    partial void Onadd_datetimeChanging(System.DateTime value);
    partial void Onadd_datetimeChanged();
    partial void Onupdate_datetimeChanging(System.DateTime value);
    partial void Onupdate_datetimeChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void Ontime_stampChanging(System.Data.Linq.Binary value);
    partial void Ontime_stampChanged();
    partial void Ondel_flagChanging(char value);
    partial void Ondel_flagChanged();
    #endregion
		
		public config_connection()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_code", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string cn_code
		{
			get
			{
				return this._cn_code;
			}
			set
			{
				if ((this._cn_code != value))
				{
					this.Oncn_codeChanging(value);
					this.SendPropertyChanging();
					this._cn_code = value;
					this.SendPropertyChanged("cn_code");
					this.Oncn_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_name", DbType="Char(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_name
		{
			get
			{
				return this._cn_name;
			}
			set
			{
				if ((this._cn_name != value))
				{
					this.Oncn_nameChanging(value);
					this.SendPropertyChanging();
					this._cn_name = value;
					this.SendPropertyChanged("cn_name");
					this.Oncn_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_server", DbType="Char(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_server
		{
			get
			{
				return this._cn_server;
			}
			set
			{
				if ((this._cn_server != value))
				{
					this.Oncn_serverChanging(value);
					this.SendPropertyChanging();
					this._cn_server = value;
					this.SendPropertyChanged("cn_server");
					this.Oncn_serverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_database", DbType="Char(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_database
		{
			get
			{
				return this._cn_database;
			}
			set
			{
				if ((this._cn_database != value))
				{
					this.Oncn_databaseChanging(value);
					this.SendPropertyChanging();
					this._cn_database = value;
					this.SendPropertyChanged("cn_database");
					this.Oncn_databaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_uid", DbType="Char(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_uid
		{
			get
			{
				return this._cn_uid;
			}
			set
			{
				if ((this._cn_uid != value))
				{
					this.Oncn_uidChanging(value);
					this.SendPropertyChanging();
					this._cn_uid = value;
					this.SendPropertyChanged("cn_uid");
					this.Oncn_uidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_pwd", DbType="Char(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_pwd
		{
			get
			{
				return this._cn_pwd;
			}
			set
			{
				if ((this._cn_pwd != value))
				{
					this.Oncn_pwdChanging(value);
					this.SendPropertyChanging();
					this._cn_pwd = value;
					this.SendPropertyChanged("cn_pwd");
					this.Oncn_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_branch_no", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_branch_no
		{
			get
			{
				return this._cn_branch_no;
			}
			set
			{
				if ((this._cn_branch_no != value))
				{
					this.Oncn_branch_noChanging(value);
					this.SendPropertyChanging();
					this._cn_branch_no = value;
					this.SendPropertyChanged("cn_branch_no");
					this.Oncn_branch_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_add", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string user_add
		{
			get
			{
				return this._user_add;
			}
			set
			{
				if ((this._user_add != value))
				{
					this.Onuser_addChanging(value);
					this.SendPropertyChanging();
					this._user_add = value;
					this.SendPropertyChanged("user_add");
					this.Onuser_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_update", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string user_update
		{
			get
			{
				return this._user_update;
			}
			set
			{
				if ((this._user_update != value))
				{
					this.Onuser_updateChanging(value);
					this.SendPropertyChanging();
					this._user_update = value;
					this.SendPropertyChanged("user_update");
					this.Onuser_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_datetime", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime add_datetime
		{
			get
			{
				return this._add_datetime;
			}
			set
			{
				if ((this._add_datetime != value))
				{
					this.Onadd_datetimeChanging(value);
					this.SendPropertyChanging();
					this._add_datetime = value;
					this.SendPropertyChanged("add_datetime");
					this.Onadd_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_datetime", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime update_datetime
		{
			get
			{
				return this._update_datetime;
			}
			set
			{
				if ((this._update_datetime != value))
				{
					this.Onupdate_datetimeChanging(value);
					this.SendPropertyChanging();
					this._update_datetime = value;
					this.SendPropertyChanged("update_datetime");
					this.Onupdate_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_stamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary time_stamp
		{
			get
			{
				return this._time_stamp;
			}
			set
			{
				if ((this._time_stamp != value))
				{
					this.Ontime_stampChanging(value);
					this.SendPropertyChanging();
					this._time_stamp = value;
					this.SendPropertyChanged("time_stamp");
					this.Ontime_stampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_del_flag", DbType="Char(1) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public char del_flag
		{
			get
			{
				return this._del_flag;
			}
			set
			{
				if ((this._del_flag != value))
				{
					this.Ondel_flagChanging(value);
					this.SendPropertyChanging();
					this._del_flag = value;
					this.SendPropertyChanged("del_flag");
					this.Ondel_flagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.df_airline")]
	public partial class df_airline
	{
		
		private string _airline_code;
		
		private char _del_flag;
		
		private string _airline_desc;
		
		private string _remark;
		
		private System.DateTime _add_datetime;
		
		private System.DateTime _update_datetime;
		
		private string _user_update;
		
		private string _user_add;
		
		private string _pickup_code;
		
		public df_airline()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airline_code", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string airline_code
		{
			get
			{
				return this._airline_code;
			}
			set
			{
				if ((this._airline_code != value))
				{
					this._airline_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_del_flag", DbType="Char(1) NOT NULL")]
		public char del_flag
		{
			get
			{
				return this._del_flag;
			}
			set
			{
				if ((this._del_flag != value))
				{
					this._del_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airline_desc", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string airline_desc
		{
			get
			{
				return this._airline_desc;
			}
			set
			{
				if ((this._airline_desc != value))
				{
					this._airline_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_datetime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime add_datetime
		{
			get
			{
				return this._add_datetime;
			}
			set
			{
				if ((this._add_datetime != value))
				{
					this._add_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_datetime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime update_datetime
		{
			get
			{
				return this._update_datetime;
			}
			set
			{
				if ((this._update_datetime != value))
				{
					this._update_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_update", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string user_update
		{
			get
			{
				return this._user_update;
			}
			set
			{
				if ((this._user_update != value))
				{
					this._user_update = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_add", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string user_add
		{
			get
			{
				return this._user_add;
			}
			set
			{
				if ((this._user_add != value))
				{
					this._user_add = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pickup_code", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string pickup_code
		{
			get
			{
				return this._pickup_code;
			}
			set
			{
				if ((this._pickup_code != value))
				{
					this._pickup_code = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.df_airport")]
	public partial class df_airport
	{
		
		private string _airport_code;
		
		private string _airport_desc;
		
		private char _del_flag;
		
		private string _remark;
		
		private System.DateTime _add_datetime;
		
		private System.DateTime _update_datetime;
		
		private string _user_add;
		
		private string _user_update;
		
		public df_airport()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airport_code", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string airport_code
		{
			get
			{
				return this._airport_code;
			}
			set
			{
				if ((this._airport_code != value))
				{
					this._airport_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airport_desc", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string airport_desc
		{
			get
			{
				return this._airport_desc;
			}
			set
			{
				if ((this._airport_desc != value))
				{
					this._airport_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_del_flag", DbType="Char(1) NOT NULL")]
		public char del_flag
		{
			get
			{
				return this._del_flag;
			}
			set
			{
				if ((this._del_flag != value))
				{
					this._del_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_datetime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime add_datetime
		{
			get
			{
				return this._add_datetime;
			}
			set
			{
				if ((this._add_datetime != value))
				{
					this._add_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_datetime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime update_datetime
		{
			get
			{
				return this._update_datetime;
			}
			set
			{
				if ((this._update_datetime != value))
				{
					this._update_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_add", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string user_add
		{
			get
			{
				return this._user_add;
			}
			set
			{
				if ((this._user_add != value))
				{
					this._user_add = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_update", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string user_update
		{
			get
			{
				return this._user_update;
			}
			set
			{
				if ((this._user_update != value))
				{
					this._user_update = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_log_interface")]
	public partial class order_log_interface : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _method;
		
		private string _api_function;
		
		private string _api_data_header;
		
		private string _api_data_detail;
		
		private string _ip_address;
		
		private System.DateTime _create_date;
		
		private EntitySet<order_transaction> _order_transactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnmethodChanging(string value);
    partial void OnmethodChanged();
    partial void Onapi_functionChanging(string value);
    partial void Onapi_functionChanged();
    partial void Onapi_data_headerChanging(string value);
    partial void Onapi_data_headerChanged();
    partial void Onapi_data_detailChanging(string value);
    partial void Onapi_data_detailChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    #endregion
		
		public order_log_interface()
		{
			this._order_transactions = new EntitySet<order_transaction>(new Action<order_transaction>(this.attach_order_transactions), new Action<order_transaction>(this.detach_order_transactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_method", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string method
		{
			get
			{
				return this._method;
			}
			set
			{
				if ((this._method != value))
				{
					this.OnmethodChanging(value);
					this.SendPropertyChanging();
					this._method = value;
					this.SendPropertyChanged("method");
					this.OnmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_api_function", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string api_function
		{
			get
			{
				return this._api_function;
			}
			set
			{
				if ((this._api_function != value))
				{
					this.Onapi_functionChanging(value);
					this.SendPropertyChanging();
					this._api_function = value;
					this.SendPropertyChanged("api_function");
					this.Onapi_functionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_api_data_header", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string api_data_header
		{
			get
			{
				return this._api_data_header;
			}
			set
			{
				if ((this._api_data_header != value))
				{
					this.Onapi_data_headerChanging(value);
					this.SendPropertyChanging();
					this._api_data_header = value;
					this.SendPropertyChanged("api_data_header");
					this.Onapi_data_headerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_api_data_detail", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string api_data_detail
		{
			get
			{
				return this._api_data_detail;
			}
			set
			{
				if ((this._api_data_detail != value))
				{
					this.Onapi_data_detailChanging(value);
					this.SendPropertyChanging();
					this._api_data_detail = value;
					this.SendPropertyChanged("api_data_detail");
					this.Onapi_data_detailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_log_interface_order_transaction", Storage="_order_transactions", ThisKey="id", OtherKey="log_id")]
		public EntitySet<order_transaction> order_transactions
		{
			get
			{
				return this._order_transactions;
			}
			set
			{
				this._order_transactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_order_transactions(order_transaction entity)
		{
			this.SendPropertyChanging();
			entity.order_log_interface = this;
		}
		
		private void detach_order_transactions(order_transaction entity)
		{
			this.SendPropertyChanging();
			entity.order_log_interface = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_session")]
	public partial class order_session : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Guid _session_guid;
		
		private string _sale_order_no;
		
		private string _sale_order_status;
		
		private string _sale_platform;
		
		private string _pos_order_no;
		
		private string _pos_order_status;
		
		private System.DateTime _create_date;
		
		private System.Nullable<System.DateTime> _modified_date;
		
		private EntitySet<order_transaction> _order_transactions;
		
		private EntitySet<order_header> _order_headers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onsession_guidChanging(System.Guid value);
    partial void Onsession_guidChanged();
    partial void Onsale_order_noChanging(string value);
    partial void Onsale_order_noChanged();
    partial void Onsale_order_statusChanging(string value);
    partial void Onsale_order_statusChanged();
    partial void Onsale_platformChanging(string value);
    partial void Onsale_platformChanged();
    partial void Onpos_order_noChanging(string value);
    partial void Onpos_order_noChanged();
    partial void Onpos_order_statusChanging(string value);
    partial void Onpos_order_statusChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    partial void Onmodified_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_dateChanged();
    #endregion
		
		public order_session()
		{
			this._order_transactions = new EntitySet<order_transaction>(new Action<order_transaction>(this.attach_order_transactions), new Action<order_transaction>(this.detach_order_transactions));
			this._order_headers = new EntitySet<order_header>(new Action<order_header>(this.attach_order_headers), new Action<order_header>(this.detach_order_headers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid session_guid
		{
			get
			{
				return this._session_guid;
			}
			set
			{
				if ((this._session_guid != value))
				{
					this.Onsession_guidChanging(value);
					this.SendPropertyChanging();
					this._session_guid = value;
					this.SendPropertyChanged("session_guid");
					this.Onsession_guidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale_order_no", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sale_order_no
		{
			get
			{
				return this._sale_order_no;
			}
			set
			{
				if ((this._sale_order_no != value))
				{
					this.Onsale_order_noChanging(value);
					this.SendPropertyChanging();
					this._sale_order_no = value;
					this.SendPropertyChanged("sale_order_no");
					this.Onsale_order_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale_order_status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sale_order_status
		{
			get
			{
				return this._sale_order_status;
			}
			set
			{
				if ((this._sale_order_status != value))
				{
					this.Onsale_order_statusChanging(value);
					this.SendPropertyChanging();
					this._sale_order_status = value;
					this.SendPropertyChanged("sale_order_status");
					this.Onsale_order_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale_platform", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sale_platform
		{
			get
			{
				return this._sale_platform;
			}
			set
			{
				if ((this._sale_platform != value))
				{
					this.Onsale_platformChanging(value);
					this.SendPropertyChanging();
					this._sale_platform = value;
					this.SendPropertyChanged("sale_platform");
					this.Onsale_platformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos_order_no", DbType="NVarChar(50)")]
		public string pos_order_no
		{
			get
			{
				return this._pos_order_no;
			}
			set
			{
				if ((this._pos_order_no != value))
				{
					this.Onpos_order_noChanging(value);
					this.SendPropertyChanging();
					this._pos_order_no = value;
					this.SendPropertyChanged("pos_order_no");
					this.Onpos_order_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos_order_status", DbType="Char(10)")]
		public string pos_order_status
		{
			get
			{
				return this._pos_order_status;
			}
			set
			{
				if ((this._pos_order_status != value))
				{
					this.Onpos_order_statusChanging(value);
					this.SendPropertyChanging();
					this._pos_order_status = value;
					this.SendPropertyChanged("pos_order_status");
					this.Onpos_order_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_date
		{
			get
			{
				return this._modified_date;
			}
			set
			{
				if ((this._modified_date != value))
				{
					this.Onmodified_dateChanging(value);
					this.SendPropertyChanging();
					this._modified_date = value;
					this.SendPropertyChanged("modified_date");
					this.Onmodified_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_session_order_transaction", Storage="_order_transactions", ThisKey="id", OtherKey="session_id")]
		public EntitySet<order_transaction> order_transactions
		{
			get
			{
				return this._order_transactions;
			}
			set
			{
				this._order_transactions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_session_order_header", Storage="_order_headers", ThisKey="id", OtherKey="session_id")]
		public EntitySet<order_header> order_headers
		{
			get
			{
				return this._order_headers;
			}
			set
			{
				this._order_headers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_order_transactions(order_transaction entity)
		{
			this.SendPropertyChanging();
			entity.order_session = this;
		}
		
		private void detach_order_transactions(order_transaction entity)
		{
			this.SendPropertyChanging();
			entity.order_session = null;
		}
		
		private void attach_order_headers(order_header entity)
		{
			this.SendPropertyChanging();
			entity.order_session = this;
		}
		
		private void detach_order_headers(order_header entity)
		{
			this.SendPropertyChanging();
			entity.order_session = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_transaction")]
	public partial class order_transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _session_id;
		
		private long _log_id;
		
		private string _datail;
		
		private System.DateTime _create_date;
		
		private EntityRef<order_log_interface> _order_log_interface;
		
		private EntityRef<order_session> _order_session;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onsession_idChanging(long value);
    partial void Onsession_idChanged();
    partial void Onlog_idChanging(long value);
    partial void Onlog_idChanged();
    partial void OndatailChanging(string value);
    partial void OndatailChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    #endregion
		
		public order_transaction()
		{
			this._order_log_interface = default(EntityRef<order_log_interface>);
			this._order_session = default(EntityRef<order_session>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_id", DbType="BigInt NOT NULL")]
		public long session_id
		{
			get
			{
				return this._session_id;
			}
			set
			{
				if ((this._session_id != value))
				{
					if (this._order_session.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsession_idChanging(value);
					this.SendPropertyChanging();
					this._session_id = value;
					this.SendPropertyChanged("session_id");
					this.Onsession_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", DbType="BigInt NOT NULL")]
		public long log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					if (this._order_log_interface.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datail", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string datail
		{
			get
			{
				return this._datail;
			}
			set
			{
				if ((this._datail != value))
				{
					this.OndatailChanging(value);
					this.SendPropertyChanging();
					this._datail = value;
					this.SendPropertyChanged("datail");
					this.OndatailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_log_interface_order_transaction", Storage="_order_log_interface", ThisKey="log_id", OtherKey="id", IsForeignKey=true)]
		public order_log_interface order_log_interface
		{
			get
			{
				return this._order_log_interface.Entity;
			}
			set
			{
				order_log_interface previousValue = this._order_log_interface.Entity;
				if (((previousValue != value) 
							|| (this._order_log_interface.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order_log_interface.Entity = null;
						previousValue.order_transactions.Remove(this);
					}
					this._order_log_interface.Entity = value;
					if ((value != null))
					{
						value.order_transactions.Add(this);
						this._log_id = value.id;
					}
					else
					{
						this._log_id = default(long);
					}
					this.SendPropertyChanged("order_log_interface");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_session_order_transaction", Storage="_order_session", ThisKey="session_id", OtherKey="id", IsForeignKey=true)]
		public order_session order_session
		{
			get
			{
				return this._order_session.Entity;
			}
			set
			{
				order_session previousValue = this._order_session.Entity;
				if (((previousValue != value) 
							|| (this._order_session.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order_session.Entity = null;
						previousValue.order_transactions.Remove(this);
					}
					this._order_session.Entity = value;
					if ((value != null))
					{
						value.order_transactions.Add(this);
						this._session_id = value.id;
					}
					else
					{
						this._session_id = default(long);
					}
					this.SendPropertyChanged("order_session");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_detail")]
	public partial class order_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _header_id;
		
		private string _sub_order_type;
		
		private string _article_code;
		
		private decimal _quantity;
		
		private decimal _selling_price;
		
		private decimal _total_amt;
		
		private System.Nullable<decimal> _dis_rate;
		
		private System.Nullable<decimal> _dis_amt;
		
		private decimal _net_amt;
		
		private string _promo_code;
		
		private string _reference_1;
		
		private string _reference_2;
		
		private string _reference_3;
		
		private EntityRef<order_header> _order_header;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onheader_idChanging(long value);
    partial void Onheader_idChanged();
    partial void Onsub_order_typeChanging(string value);
    partial void Onsub_order_typeChanged();
    partial void Onarticle_codeChanging(string value);
    partial void Onarticle_codeChanged();
    partial void OnquantityChanging(decimal value);
    partial void OnquantityChanged();
    partial void Onselling_priceChanging(decimal value);
    partial void Onselling_priceChanged();
    partial void Ontotal_amtChanging(decimal value);
    partial void Ontotal_amtChanged();
    partial void Ondis_rateChanging(System.Nullable<decimal> value);
    partial void Ondis_rateChanged();
    partial void Ondis_amtChanging(System.Nullable<decimal> value);
    partial void Ondis_amtChanged();
    partial void Onnet_amtChanging(decimal value);
    partial void Onnet_amtChanged();
    partial void Onpromo_codeChanging(string value);
    partial void Onpromo_codeChanged();
    partial void Onreference_1Changing(string value);
    partial void Onreference_1Changed();
    partial void Onreference_2Changing(string value);
    partial void Onreference_2Changed();
    partial void Onreference_3Changing(string value);
    partial void Onreference_3Changed();
    #endregion
		
		public order_detail()
		{
			this._order_header = default(EntityRef<order_header>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_header_id", DbType="BigInt NOT NULL")]
		public long header_id
		{
			get
			{
				return this._header_id;
			}
			set
			{
				if ((this._header_id != value))
				{
					if (this._order_header.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onheader_idChanging(value);
					this.SendPropertyChanging();
					this._header_id = value;
					this.SendPropertyChanged("header_id");
					this.Onheader_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_order_type", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string sub_order_type
		{
			get
			{
				return this._sub_order_type;
			}
			set
			{
				if ((this._sub_order_type != value))
				{
					this.Onsub_order_typeChanging(value);
					this.SendPropertyChanging();
					this._sub_order_type = value;
					this.SendPropertyChanged("sub_order_type");
					this.Onsub_order_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_article_code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string article_code
		{
			get
			{
				return this._article_code;
			}
			set
			{
				if ((this._article_code != value))
				{
					this.Onarticle_codeChanging(value);
					this.SendPropertyChanging();
					this._article_code = value;
					this.SendPropertyChanged("article_code");
					this.Onarticle_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Decimal(18,0) NOT NULL")]
		public decimal quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selling_price", DbType="Decimal(18,0) NOT NULL")]
		public decimal selling_price
		{
			get
			{
				return this._selling_price;
			}
			set
			{
				if ((this._selling_price != value))
				{
					this.Onselling_priceChanging(value);
					this.SendPropertyChanging();
					this._selling_price = value;
					this.SendPropertyChanged("selling_price");
					this.Onselling_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_amt", DbType="Decimal(18,0) NOT NULL")]
		public decimal total_amt
		{
			get
			{
				return this._total_amt;
			}
			set
			{
				if ((this._total_amt != value))
				{
					this.Ontotal_amtChanging(value);
					this.SendPropertyChanging();
					this._total_amt = value;
					this.SendPropertyChanged("total_amt");
					this.Ontotal_amtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dis_rate", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> dis_rate
		{
			get
			{
				return this._dis_rate;
			}
			set
			{
				if ((this._dis_rate != value))
				{
					this.Ondis_rateChanging(value);
					this.SendPropertyChanging();
					this._dis_rate = value;
					this.SendPropertyChanged("dis_rate");
					this.Ondis_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dis_amt", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> dis_amt
		{
			get
			{
				return this._dis_amt;
			}
			set
			{
				if ((this._dis_amt != value))
				{
					this.Ondis_amtChanging(value);
					this.SendPropertyChanging();
					this._dis_amt = value;
					this.SendPropertyChanged("dis_amt");
					this.Ondis_amtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_net_amt", DbType="Decimal(18,0) NOT NULL")]
		public decimal net_amt
		{
			get
			{
				return this._net_amt;
			}
			set
			{
				if ((this._net_amt != value))
				{
					this.Onnet_amtChanging(value);
					this.SendPropertyChanging();
					this._net_amt = value;
					this.SendPropertyChanged("net_amt");
					this.Onnet_amtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_promo_code", DbType="NVarChar(50)")]
		public string promo_code
		{
			get
			{
				return this._promo_code;
			}
			set
			{
				if ((this._promo_code != value))
				{
					this.Onpromo_codeChanging(value);
					this.SendPropertyChanging();
					this._promo_code = value;
					this.SendPropertyChanged("promo_code");
					this.Onpromo_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference_1", DbType="NVarChar(50)")]
		public string reference_1
		{
			get
			{
				return this._reference_1;
			}
			set
			{
				if ((this._reference_1 != value))
				{
					this.Onreference_1Changing(value);
					this.SendPropertyChanging();
					this._reference_1 = value;
					this.SendPropertyChanged("reference_1");
					this.Onreference_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference_2", DbType="NVarChar(50)")]
		public string reference_2
		{
			get
			{
				return this._reference_2;
			}
			set
			{
				if ((this._reference_2 != value))
				{
					this.Onreference_2Changing(value);
					this.SendPropertyChanging();
					this._reference_2 = value;
					this.SendPropertyChanged("reference_2");
					this.Onreference_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference_3", DbType="NVarChar(50)")]
		public string reference_3
		{
			get
			{
				return this._reference_3;
			}
			set
			{
				if ((this._reference_3 != value))
				{
					this.Onreference_3Changing(value);
					this.SendPropertyChanging();
					this._reference_3 = value;
					this.SendPropertyChanged("reference_3");
					this.Onreference_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_header_order_detail", Storage="_order_header", ThisKey="header_id", OtherKey="id", IsForeignKey=true)]
		public order_header order_header
		{
			get
			{
				return this._order_header.Entity;
			}
			set
			{
				order_header previousValue = this._order_header.Entity;
				if (((previousValue != value) 
							|| (this._order_header.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order_header.Entity = null;
						previousValue.order_details.Remove(this);
					}
					this._order_header.Entity = value;
					if ((value != null))
					{
						value.order_details.Add(this);
						this._header_id = value.id;
					}
					else
					{
						this._header_id = default(long);
					}
					this.SendPropertyChanged("order_header");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_discount")]
	public partial class order_discount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _header_id;
		
		private string _dis_type;
		
		private string _dis_code;
		
		private System.Nullable<decimal> _dis_rate;
		
		private System.Nullable<decimal> _dis_amt;
		
		private EntityRef<order_header> _order_header;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onheader_idChanging(long value);
    partial void Onheader_idChanged();
    partial void Ondis_typeChanging(string value);
    partial void Ondis_typeChanged();
    partial void Ondis_codeChanging(string value);
    partial void Ondis_codeChanged();
    partial void Ondis_rateChanging(System.Nullable<decimal> value);
    partial void Ondis_rateChanged();
    partial void Ondis_amtChanging(System.Nullable<decimal> value);
    partial void Ondis_amtChanged();
    #endregion
		
		public order_discount()
		{
			this._order_header = default(EntityRef<order_header>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_header_id", DbType="BigInt NOT NULL")]
		public long header_id
		{
			get
			{
				return this._header_id;
			}
			set
			{
				if ((this._header_id != value))
				{
					if (this._order_header.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onheader_idChanging(value);
					this.SendPropertyChanging();
					this._header_id = value;
					this.SendPropertyChanged("header_id");
					this.Onheader_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dis_type", DbType="NVarChar(50)")]
		public string dis_type
		{
			get
			{
				return this._dis_type;
			}
			set
			{
				if ((this._dis_type != value))
				{
					this.Ondis_typeChanging(value);
					this.SendPropertyChanging();
					this._dis_type = value;
					this.SendPropertyChanged("dis_type");
					this.Ondis_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dis_code", DbType="NVarChar(50)")]
		public string dis_code
		{
			get
			{
				return this._dis_code;
			}
			set
			{
				if ((this._dis_code != value))
				{
					this.Ondis_codeChanging(value);
					this.SendPropertyChanging();
					this._dis_code = value;
					this.SendPropertyChanged("dis_code");
					this.Ondis_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dis_rate", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> dis_rate
		{
			get
			{
				return this._dis_rate;
			}
			set
			{
				if ((this._dis_rate != value))
				{
					this.Ondis_rateChanging(value);
					this.SendPropertyChanging();
					this._dis_rate = value;
					this.SendPropertyChanged("dis_rate");
					this.Ondis_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dis_amt", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> dis_amt
		{
			get
			{
				return this._dis_amt;
			}
			set
			{
				if ((this._dis_amt != value))
				{
					this.Ondis_amtChanging(value);
					this.SendPropertyChanging();
					this._dis_amt = value;
					this.SendPropertyChanged("dis_amt");
					this.Ondis_amtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_header_order_discount", Storage="_order_header", ThisKey="header_id", OtherKey="id", IsForeignKey=true)]
		public order_header order_header
		{
			get
			{
				return this._order_header.Entity;
			}
			set
			{
				order_header previousValue = this._order_header.Entity;
				if (((previousValue != value) 
							|| (this._order_header.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order_header.Entity = null;
						previousValue.order_discounts.Remove(this);
					}
					this._order_header.Entity = value;
					if ((value != null))
					{
						value.order_discounts.Add(this);
						this._header_id = value.id;
					}
					else
					{
						this._header_id = default(long);
					}
					this.SendPropertyChanged("order_header");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_header")]
	public partial class order_header : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _session_id;
		
		private string _order_type;
		
		private string _member_id;
		
		private string _full_name;
		
		private string _passport_no;
		
		private string _country;
		
		private string _airport_code;
		
		private string _terminal_code;
		
		private string _airline_code;
		
		private string _flight_code;
		
		private string _flight_no;
		
		private string _reference_1;
		
		private string _reference_2;
		
		private string _reference_3;
		
		private string _remark;
		
		private System.DateTime _create_date;
		
		private EntitySet<order_detail> _order_details;
		
		private EntitySet<order_discount> _order_discounts;
		
		private EntitySet<order_payment> _order_payments;
		
		private EntityRef<order_session> _order_session;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onsession_idChanging(long value);
    partial void Onsession_idChanged();
    partial void Onorder_typeChanging(string value);
    partial void Onorder_typeChanged();
    partial void Onmember_idChanging(string value);
    partial void Onmember_idChanged();
    partial void Onfull_nameChanging(string value);
    partial void Onfull_nameChanged();
    partial void Onpassport_noChanging(string value);
    partial void Onpassport_noChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void Onairport_codeChanging(string value);
    partial void Onairport_codeChanged();
    partial void Onterminal_codeChanging(string value);
    partial void Onterminal_codeChanged();
    partial void Onairline_codeChanging(string value);
    partial void Onairline_codeChanged();
    partial void Onflight_codeChanging(string value);
    partial void Onflight_codeChanged();
    partial void Onflight_noChanging(string value);
    partial void Onflight_noChanged();
    partial void Onreference_1Changing(string value);
    partial void Onreference_1Changed();
    partial void Onreference_2Changing(string value);
    partial void Onreference_2Changed();
    partial void Onreference_3Changing(string value);
    partial void Onreference_3Changed();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    #endregion
		
		public order_header()
		{
			this._order_details = new EntitySet<order_detail>(new Action<order_detail>(this.attach_order_details), new Action<order_detail>(this.detach_order_details));
			this._order_discounts = new EntitySet<order_discount>(new Action<order_discount>(this.attach_order_discounts), new Action<order_discount>(this.detach_order_discounts));
			this._order_payments = new EntitySet<order_payment>(new Action<order_payment>(this.attach_order_payments), new Action<order_payment>(this.detach_order_payments));
			this._order_session = default(EntityRef<order_session>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_id", DbType="BigInt NOT NULL")]
		public long session_id
		{
			get
			{
				return this._session_id;
			}
			set
			{
				if ((this._session_id != value))
				{
					if (this._order_session.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsession_idChanging(value);
					this.SendPropertyChanging();
					this._session_id = value;
					this.SendPropertyChanged("session_id");
					this.Onsession_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_type", DbType="Char(10)")]
		public string order_type
		{
			get
			{
				return this._order_type;
			}
			set
			{
				if ((this._order_type != value))
				{
					this.Onorder_typeChanging(value);
					this.SendPropertyChanging();
					this._order_type = value;
					this.SendPropertyChanged("order_type");
					this.Onorder_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_member_id", DbType="NVarChar(50)")]
		public string member_id
		{
			get
			{
				return this._member_id;
			}
			set
			{
				if ((this._member_id != value))
				{
					this.Onmember_idChanging(value);
					this.SendPropertyChanging();
					this._member_id = value;
					this.SendPropertyChanged("member_id");
					this.Onmember_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="NVarChar(50)")]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this.Onfull_nameChanging(value);
					this.SendPropertyChanging();
					this._full_name = value;
					this.SendPropertyChanged("full_name");
					this.Onfull_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passport_no", DbType="NVarChar(50)")]
		public string passport_no
		{
			get
			{
				return this._passport_no;
			}
			set
			{
				if ((this._passport_no != value))
				{
					this.Onpassport_noChanging(value);
					this.SendPropertyChanging();
					this._passport_no = value;
					this.SendPropertyChanged("passport_no");
					this.Onpassport_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NChar(10)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airport_code", DbType="NChar(10)")]
		public string airport_code
		{
			get
			{
				return this._airport_code;
			}
			set
			{
				if ((this._airport_code != value))
				{
					this.Onairport_codeChanging(value);
					this.SendPropertyChanging();
					this._airport_code = value;
					this.SendPropertyChanged("airport_code");
					this.Onairport_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terminal_code", DbType="NChar(10)")]
		public string terminal_code
		{
			get
			{
				return this._terminal_code;
			}
			set
			{
				if ((this._terminal_code != value))
				{
					this.Onterminal_codeChanging(value);
					this.SendPropertyChanging();
					this._terminal_code = value;
					this.SendPropertyChanged("terminal_code");
					this.Onterminal_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airline_code", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string airline_code
		{
			get
			{
				return this._airline_code;
			}
			set
			{
				if ((this._airline_code != value))
				{
					this.Onairline_codeChanging(value);
					this.SendPropertyChanging();
					this._airline_code = value;
					this.SendPropertyChanged("airline_code");
					this.Onairline_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_code", DbType="NChar(10)")]
		public string flight_code
		{
			get
			{
				return this._flight_code;
			}
			set
			{
				if ((this._flight_code != value))
				{
					this.Onflight_codeChanging(value);
					this.SendPropertyChanging();
					this._flight_code = value;
					this.SendPropertyChanged("flight_code");
					this.Onflight_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_no", DbType="NChar(10)")]
		public string flight_no
		{
			get
			{
				return this._flight_no;
			}
			set
			{
				if ((this._flight_no != value))
				{
					this.Onflight_noChanging(value);
					this.SendPropertyChanging();
					this._flight_no = value;
					this.SendPropertyChanged("flight_no");
					this.Onflight_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference_1", DbType="NVarChar(50)")]
		public string reference_1
		{
			get
			{
				return this._reference_1;
			}
			set
			{
				if ((this._reference_1 != value))
				{
					this.Onreference_1Changing(value);
					this.SendPropertyChanging();
					this._reference_1 = value;
					this.SendPropertyChanged("reference_1");
					this.Onreference_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference_2", DbType="NVarChar(50)")]
		public string reference_2
		{
			get
			{
				return this._reference_2;
			}
			set
			{
				if ((this._reference_2 != value))
				{
					this.Onreference_2Changing(value);
					this.SendPropertyChanging();
					this._reference_2 = value;
					this.SendPropertyChanged("reference_2");
					this.Onreference_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference_3", DbType="NVarChar(50)")]
		public string reference_3
		{
			get
			{
				return this._reference_3;
			}
			set
			{
				if ((this._reference_3 != value))
				{
					this.Onreference_3Changing(value);
					this.SendPropertyChanging();
					this._reference_3 = value;
					this.SendPropertyChanged("reference_3");
					this.Onreference_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_header_order_detail", Storage="_order_details", ThisKey="id", OtherKey="header_id")]
		public EntitySet<order_detail> order_details
		{
			get
			{
				return this._order_details;
			}
			set
			{
				this._order_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_header_order_discount", Storage="_order_discounts", ThisKey="id", OtherKey="header_id")]
		public EntitySet<order_discount> order_discounts
		{
			get
			{
				return this._order_discounts;
			}
			set
			{
				this._order_discounts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_header_order_payment", Storage="_order_payments", ThisKey="id", OtherKey="header_id")]
		public EntitySet<order_payment> order_payments
		{
			get
			{
				return this._order_payments;
			}
			set
			{
				this._order_payments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_session_order_header", Storage="_order_session", ThisKey="session_id", OtherKey="id", IsForeignKey=true)]
		public order_session order_session
		{
			get
			{
				return this._order_session.Entity;
			}
			set
			{
				order_session previousValue = this._order_session.Entity;
				if (((previousValue != value) 
							|| (this._order_session.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order_session.Entity = null;
						previousValue.order_headers.Remove(this);
					}
					this._order_session.Entity = value;
					if ((value != null))
					{
						value.order_headers.Add(this);
						this._session_id = value.id;
					}
					else
					{
						this._session_id = default(long);
					}
					this.SendPropertyChanged("order_session");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_order_details(order_detail entity)
		{
			this.SendPropertyChanging();
			entity.order_header = this;
		}
		
		private void detach_order_details(order_detail entity)
		{
			this.SendPropertyChanging();
			entity.order_header = null;
		}
		
		private void attach_order_discounts(order_discount entity)
		{
			this.SendPropertyChanging();
			entity.order_header = this;
		}
		
		private void detach_order_discounts(order_discount entity)
		{
			this.SendPropertyChanging();
			entity.order_header = null;
		}
		
		private void attach_order_payments(order_payment entity)
		{
			this.SendPropertyChanging();
			entity.order_header = this;
		}
		
		private void detach_order_payments(order_payment entity)
		{
			this.SendPropertyChanging();
			entity.order_header = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_payment")]
	public partial class order_payment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _header_id;
		
		private string _payment_type;
		
		private string _paymemt_agent;
		
		private string _paymemt_session_id;
		
		private string _paymemt_ref_no;
		
		private string _payment_code;
		
		private System.Nullable<decimal> _paymemt_amt;
		
		private System.Nullable<System.DateTime> _paymemt_datetime;
		
		private EntityRef<order_header> _order_header;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onheader_idChanging(long value);
    partial void Onheader_idChanged();
    partial void Onpayment_typeChanging(string value);
    partial void Onpayment_typeChanged();
    partial void Onpaymemt_agentChanging(string value);
    partial void Onpaymemt_agentChanged();
    partial void Onpaymemt_session_idChanging(string value);
    partial void Onpaymemt_session_idChanged();
    partial void Onpaymemt_ref_noChanging(string value);
    partial void Onpaymemt_ref_noChanged();
    partial void Onpayment_codeChanging(string value);
    partial void Onpayment_codeChanged();
    partial void Onpaymemt_amtChanging(System.Nullable<decimal> value);
    partial void Onpaymemt_amtChanged();
    partial void Onpaymemt_datetimeChanging(System.Nullable<System.DateTime> value);
    partial void Onpaymemt_datetimeChanged();
    #endregion
		
		public order_payment()
		{
			this._order_header = default(EntityRef<order_header>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_header_id", DbType="BigInt NOT NULL")]
		public long header_id
		{
			get
			{
				return this._header_id;
			}
			set
			{
				if ((this._header_id != value))
				{
					if (this._order_header.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onheader_idChanging(value);
					this.SendPropertyChanging();
					this._header_id = value;
					this.SendPropertyChanged("header_id");
					this.Onheader_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_type", DbType="NChar(10)")]
		public string payment_type
		{
			get
			{
				return this._payment_type;
			}
			set
			{
				if ((this._payment_type != value))
				{
					this.Onpayment_typeChanging(value);
					this.SendPropertyChanging();
					this._payment_type = value;
					this.SendPropertyChanged("payment_type");
					this.Onpayment_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymemt_agent", DbType="NChar(10)")]
		public string paymemt_agent
		{
			get
			{
				return this._paymemt_agent;
			}
			set
			{
				if ((this._paymemt_agent != value))
				{
					this.Onpaymemt_agentChanging(value);
					this.SendPropertyChanging();
					this._paymemt_agent = value;
					this.SendPropertyChanged("paymemt_agent");
					this.Onpaymemt_agentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymemt_session_id", DbType="NVarChar(50)")]
		public string paymemt_session_id
		{
			get
			{
				return this._paymemt_session_id;
			}
			set
			{
				if ((this._paymemt_session_id != value))
				{
					this.Onpaymemt_session_idChanging(value);
					this.SendPropertyChanging();
					this._paymemt_session_id = value;
					this.SendPropertyChanged("paymemt_session_id");
					this.Onpaymemt_session_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymemt_ref_no", DbType="NVarChar(50)")]
		public string paymemt_ref_no
		{
			get
			{
				return this._paymemt_ref_no;
			}
			set
			{
				if ((this._paymemt_ref_no != value))
				{
					this.Onpaymemt_ref_noChanging(value);
					this.SendPropertyChanging();
					this._paymemt_ref_no = value;
					this.SendPropertyChanged("paymemt_ref_no");
					this.Onpaymemt_ref_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_code", DbType="NChar(10)")]
		public string payment_code
		{
			get
			{
				return this._payment_code;
			}
			set
			{
				if ((this._payment_code != value))
				{
					this.Onpayment_codeChanging(value);
					this.SendPropertyChanging();
					this._payment_code = value;
					this.SendPropertyChanged("payment_code");
					this.Onpayment_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymemt_amt", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> paymemt_amt
		{
			get
			{
				return this._paymemt_amt;
			}
			set
			{
				if ((this._paymemt_amt != value))
				{
					this.Onpaymemt_amtChanging(value);
					this.SendPropertyChanging();
					this._paymemt_amt = value;
					this.SendPropertyChanged("paymemt_amt");
					this.Onpaymemt_amtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymemt_datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> paymemt_datetime
		{
			get
			{
				return this._paymemt_datetime;
			}
			set
			{
				if ((this._paymemt_datetime != value))
				{
					this.Onpaymemt_datetimeChanging(value);
					this.SendPropertyChanging();
					this._paymemt_datetime = value;
					this.SendPropertyChanged("paymemt_datetime");
					this.Onpaymemt_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_header_order_payment", Storage="_order_header", ThisKey="header_id", OtherKey="id", IsForeignKey=true)]
		public order_header order_header
		{
			get
			{
				return this._order_header.Entity;
			}
			set
			{
				order_header previousValue = this._order_header.Entity;
				if (((previousValue != value) 
							|| (this._order_header.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order_header.Entity = null;
						previousValue.order_payments.Remove(this);
					}
					this._order_header.Entity = value;
					if ((value != null))
					{
						value.order_payments.Add(this);
						this._header_id = value.id;
					}
					else
					{
						this._header_id = default(long);
					}
					this.SendPropertyChanged("order_header");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
