#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.OrderMGT.BL.DBModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KPOrder")]
	public partial class OrderDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertconfig_connection(config_connection instance);
    partial void Updateconfig_connection(config_connection instance);
    partial void Deleteconfig_connection(config_connection instance);
    partial void Insertorder_log_interface(order_log_interface instance);
    partial void Updateorder_log_interface(order_log_interface instance);
    partial void Deleteorder_log_interface(order_log_interface instance);
    partial void Insertorder_session(order_session instance);
    partial void Updateorder_session(order_session instance);
    partial void Deleteorder_session(order_session instance);
    partial void Insertorder_transaction(order_transaction instance);
    partial void Updateorder_transaction(order_transaction instance);
    partial void Deleteorder_transaction(order_transaction instance);
    #endregion
		
		public OrderDataClassesDataContext() : 
				base(global::KP.OrderMGT.BL.Properties.Settings.Default.KPOrderConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<df_flight> df_flights
		{
			get
			{
				return this.GetTable<df_flight>();
			}
		}
		
		public System.Data.Linq.Table<config_connection> config_connections
		{
			get
			{
				return this.GetTable<config_connection>();
			}
		}
		
		public System.Data.Linq.Table<df_airline> df_airlines
		{
			get
			{
				return this.GetTable<df_airline>();
			}
		}
		
		public System.Data.Linq.Table<df_airport> df_airports
		{
			get
			{
				return this.GetTable<df_airport>();
			}
		}
		
		public System.Data.Linq.Table<order_log_interface> order_log_interfaces
		{
			get
			{
				return this.GetTable<order_log_interface>();
			}
		}
		
		public System.Data.Linq.Table<order_session> order_sessions
		{
			get
			{
				return this.GetTable<order_session>();
			}
		}
		
		public System.Data.Linq.Table<order_transaction> order_transactions
		{
			get
			{
				return this.GetTable<order_transaction>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.df_flight")]
	public partial class df_flight
	{
		
		private string _flight_code;
		
		private char _del_flag;
		
		private string _flight_desc;
		
		private string _dest_airport_code;
		
		private string _arrdep_airport_code;
		
		private string _arrdep_terminal;
		
		private bool _d2;
		
		private bool _d3;
		
		private bool _d4;
		
		private bool _d5;
		
		private bool _d6;
		
		private bool _d7;
		
		private bool _d1;
		
		private string _arrdep_time;
		
		private bool _open_flight;
		
		private string _remark;
		
		private System.DateTime _add_datetime;
		
		private System.DateTime _update_datetime;
		
		private string _user_add;
		
		private string _user_update;
		
		private System.Data.Linq.Binary _time_stamp;
		
		private int _CutOffTime;
		
		private string _pickup_code;
		
		public df_flight()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_code", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string flight_code
		{
			get
			{
				return this._flight_code;
			}
			set
			{
				if ((this._flight_code != value))
				{
					this._flight_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_del_flag", DbType="Char(1) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public char del_flag
		{
			get
			{
				return this._del_flag;
			}
			set
			{
				if ((this._del_flag != value))
				{
					this._del_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_desc", DbType="Char(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string flight_desc
		{
			get
			{
				return this._flight_desc;
			}
			set
			{
				if ((this._flight_desc != value))
				{
					this._flight_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dest_airport_code", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string dest_airport_code
		{
			get
			{
				return this._dest_airport_code;
			}
			set
			{
				if ((this._dest_airport_code != value))
				{
					this._dest_airport_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrdep_airport_code", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string arrdep_airport_code
		{
			get
			{
				return this._arrdep_airport_code;
			}
			set
			{
				if ((this._arrdep_airport_code != value))
				{
					this._arrdep_airport_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrdep_terminal", DbType="Char(5)", UpdateCheck=UpdateCheck.Never)]
		public string arrdep_terminal
		{
			get
			{
				return this._arrdep_terminal;
			}
			set
			{
				if ((this._arrdep_terminal != value))
				{
					this._arrdep_terminal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d2", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d2
		{
			get
			{
				return this._d2;
			}
			set
			{
				if ((this._d2 != value))
				{
					this._d2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d3", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d3
		{
			get
			{
				return this._d3;
			}
			set
			{
				if ((this._d3 != value))
				{
					this._d3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d4", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d4
		{
			get
			{
				return this._d4;
			}
			set
			{
				if ((this._d4 != value))
				{
					this._d4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d5", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d5
		{
			get
			{
				return this._d5;
			}
			set
			{
				if ((this._d5 != value))
				{
					this._d5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d6", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d6
		{
			get
			{
				return this._d6;
			}
			set
			{
				if ((this._d6 != value))
				{
					this._d6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d7", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d7
		{
			get
			{
				return this._d7;
			}
			set
			{
				if ((this._d7 != value))
				{
					this._d7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d1", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool d1
		{
			get
			{
				return this._d1;
			}
			set
			{
				if ((this._d1 != value))
				{
					this._d1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrdep_time", DbType="Char(5) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string arrdep_time
		{
			get
			{
				return this._arrdep_time;
			}
			set
			{
				if ((this._arrdep_time != value))
				{
					this._arrdep_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_open_flight", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool open_flight
		{
			get
			{
				return this._open_flight;
			}
			set
			{
				if ((this._open_flight != value))
				{
					this._open_flight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_datetime", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime add_datetime
		{
			get
			{
				return this._add_datetime;
			}
			set
			{
				if ((this._add_datetime != value))
				{
					this._add_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_datetime", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime update_datetime
		{
			get
			{
				return this._update_datetime;
			}
			set
			{
				if ((this._update_datetime != value))
				{
					this._update_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_add", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string user_add
		{
			get
			{
				return this._user_add;
			}
			set
			{
				if ((this._user_add != value))
				{
					this._user_add = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_update", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string user_update
		{
			get
			{
				return this._user_update;
			}
			set
			{
				if ((this._user_update != value))
				{
					this._user_update = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_stamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary time_stamp
		{
			get
			{
				return this._time_stamp;
			}
			set
			{
				if ((this._time_stamp != value))
				{
					this._time_stamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CutOffTime", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CutOffTime
		{
			get
			{
				return this._CutOffTime;
			}
			set
			{
				if ((this._CutOffTime != value))
				{
					this._CutOffTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pickup_code", DbType="Char(10)", UpdateCheck=UpdateCheck.Never)]
		public string pickup_code
		{
			get
			{
				return this._pickup_code;
			}
			set
			{
				if ((this._pickup_code != value))
				{
					this._pickup_code = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.config_connection")]
	public partial class config_connection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cn_code;
		
		private string _cn_name;
		
		private string _cn_server;
		
		private string _cn_database;
		
		private string _cn_uid;
		
		private string _cn_pwd;
		
		private string _cn_branch_no;
		
		private string _user_add;
		
		private string _user_update;
		
		private System.DateTime _add_datetime;
		
		private System.DateTime _update_datetime;
		
		private string _remark;
		
		private System.Data.Linq.Binary _time_stamp;
		
		private char _del_flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncn_codeChanging(string value);
    partial void Oncn_codeChanged();
    partial void Oncn_nameChanging(string value);
    partial void Oncn_nameChanged();
    partial void Oncn_serverChanging(string value);
    partial void Oncn_serverChanged();
    partial void Oncn_databaseChanging(string value);
    partial void Oncn_databaseChanged();
    partial void Oncn_uidChanging(string value);
    partial void Oncn_uidChanged();
    partial void Oncn_pwdChanging(string value);
    partial void Oncn_pwdChanged();
    partial void Oncn_branch_noChanging(string value);
    partial void Oncn_branch_noChanged();
    partial void Onuser_addChanging(string value);
    partial void Onuser_addChanged();
    partial void Onuser_updateChanging(string value);
    partial void Onuser_updateChanged();
    partial void Onadd_datetimeChanging(System.DateTime value);
    partial void Onadd_datetimeChanged();
    partial void Onupdate_datetimeChanging(System.DateTime value);
    partial void Onupdate_datetimeChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void Ontime_stampChanging(System.Data.Linq.Binary value);
    partial void Ontime_stampChanged();
    partial void Ondel_flagChanging(char value);
    partial void Ondel_flagChanged();
    #endregion
		
		public config_connection()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_code", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string cn_code
		{
			get
			{
				return this._cn_code;
			}
			set
			{
				if ((this._cn_code != value))
				{
					this.Oncn_codeChanging(value);
					this.SendPropertyChanging();
					this._cn_code = value;
					this.SendPropertyChanged("cn_code");
					this.Oncn_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_name", DbType="Char(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_name
		{
			get
			{
				return this._cn_name;
			}
			set
			{
				if ((this._cn_name != value))
				{
					this.Oncn_nameChanging(value);
					this.SendPropertyChanging();
					this._cn_name = value;
					this.SendPropertyChanged("cn_name");
					this.Oncn_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_server", DbType="Char(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_server
		{
			get
			{
				return this._cn_server;
			}
			set
			{
				if ((this._cn_server != value))
				{
					this.Oncn_serverChanging(value);
					this.SendPropertyChanging();
					this._cn_server = value;
					this.SendPropertyChanged("cn_server");
					this.Oncn_serverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_database", DbType="Char(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_database
		{
			get
			{
				return this._cn_database;
			}
			set
			{
				if ((this._cn_database != value))
				{
					this.Oncn_databaseChanging(value);
					this.SendPropertyChanging();
					this._cn_database = value;
					this.SendPropertyChanged("cn_database");
					this.Oncn_databaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_uid", DbType="Char(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_uid
		{
			get
			{
				return this._cn_uid;
			}
			set
			{
				if ((this._cn_uid != value))
				{
					this.Oncn_uidChanging(value);
					this.SendPropertyChanging();
					this._cn_uid = value;
					this.SendPropertyChanged("cn_uid");
					this.Oncn_uidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_pwd", DbType="Char(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_pwd
		{
			get
			{
				return this._cn_pwd;
			}
			set
			{
				if ((this._cn_pwd != value))
				{
					this.Oncn_pwdChanging(value);
					this.SendPropertyChanging();
					this._cn_pwd = value;
					this.SendPropertyChanged("cn_pwd");
					this.Oncn_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn_branch_no", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cn_branch_no
		{
			get
			{
				return this._cn_branch_no;
			}
			set
			{
				if ((this._cn_branch_no != value))
				{
					this.Oncn_branch_noChanging(value);
					this.SendPropertyChanging();
					this._cn_branch_no = value;
					this.SendPropertyChanged("cn_branch_no");
					this.Oncn_branch_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_add", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string user_add
		{
			get
			{
				return this._user_add;
			}
			set
			{
				if ((this._user_add != value))
				{
					this.Onuser_addChanging(value);
					this.SendPropertyChanging();
					this._user_add = value;
					this.SendPropertyChanged("user_add");
					this.Onuser_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_update", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string user_update
		{
			get
			{
				return this._user_update;
			}
			set
			{
				if ((this._user_update != value))
				{
					this.Onuser_updateChanging(value);
					this.SendPropertyChanging();
					this._user_update = value;
					this.SendPropertyChanged("user_update");
					this.Onuser_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_datetime", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime add_datetime
		{
			get
			{
				return this._add_datetime;
			}
			set
			{
				if ((this._add_datetime != value))
				{
					this.Onadd_datetimeChanging(value);
					this.SendPropertyChanging();
					this._add_datetime = value;
					this.SendPropertyChanged("add_datetime");
					this.Onadd_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_datetime", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime update_datetime
		{
			get
			{
				return this._update_datetime;
			}
			set
			{
				if ((this._update_datetime != value))
				{
					this.Onupdate_datetimeChanging(value);
					this.SendPropertyChanging();
					this._update_datetime = value;
					this.SendPropertyChanged("update_datetime");
					this.Onupdate_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_stamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary time_stamp
		{
			get
			{
				return this._time_stamp;
			}
			set
			{
				if ((this._time_stamp != value))
				{
					this.Ontime_stampChanging(value);
					this.SendPropertyChanging();
					this._time_stamp = value;
					this.SendPropertyChanged("time_stamp");
					this.Ontime_stampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_del_flag", DbType="Char(1) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public char del_flag
		{
			get
			{
				return this._del_flag;
			}
			set
			{
				if ((this._del_flag != value))
				{
					this.Ondel_flagChanging(value);
					this.SendPropertyChanging();
					this._del_flag = value;
					this.SendPropertyChanged("del_flag");
					this.Ondel_flagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.df_airline")]
	public partial class df_airline
	{
		
		private string _airline_code;
		
		private char _del_flag;
		
		private string _airline_desc;
		
		private string _remark;
		
		private System.DateTime _add_datetime;
		
		private System.DateTime _update_datetime;
		
		private string _user_update;
		
		private string _user_add;
		
		private string _pickup_code;
		
		public df_airline()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airline_code", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string airline_code
		{
			get
			{
				return this._airline_code;
			}
			set
			{
				if ((this._airline_code != value))
				{
					this._airline_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_del_flag", DbType="Char(1) NOT NULL")]
		public char del_flag
		{
			get
			{
				return this._del_flag;
			}
			set
			{
				if ((this._del_flag != value))
				{
					this._del_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airline_desc", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string airline_desc
		{
			get
			{
				return this._airline_desc;
			}
			set
			{
				if ((this._airline_desc != value))
				{
					this._airline_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_datetime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime add_datetime
		{
			get
			{
				return this._add_datetime;
			}
			set
			{
				if ((this._add_datetime != value))
				{
					this._add_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_datetime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime update_datetime
		{
			get
			{
				return this._update_datetime;
			}
			set
			{
				if ((this._update_datetime != value))
				{
					this._update_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_update", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string user_update
		{
			get
			{
				return this._user_update;
			}
			set
			{
				if ((this._user_update != value))
				{
					this._user_update = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_add", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string user_add
		{
			get
			{
				return this._user_add;
			}
			set
			{
				if ((this._user_add != value))
				{
					this._user_add = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pickup_code", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string pickup_code
		{
			get
			{
				return this._pickup_code;
			}
			set
			{
				if ((this._pickup_code != value))
				{
					this._pickup_code = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.df_airport")]
	public partial class df_airport
	{
		
		private string _airport_code;
		
		private string _airport_desc;
		
		private char _del_flag;
		
		private string _remark;
		
		private System.DateTime _add_datetime;
		
		private System.DateTime _update_datetime;
		
		private string _user_add;
		
		private string _user_update;
		
		public df_airport()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airport_code", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string airport_code
		{
			get
			{
				return this._airport_code;
			}
			set
			{
				if ((this._airport_code != value))
				{
					this._airport_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airport_desc", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string airport_desc
		{
			get
			{
				return this._airport_desc;
			}
			set
			{
				if ((this._airport_desc != value))
				{
					this._airport_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_del_flag", DbType="Char(1) NOT NULL")]
		public char del_flag
		{
			get
			{
				return this._del_flag;
			}
			set
			{
				if ((this._del_flag != value))
				{
					this._del_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_datetime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime add_datetime
		{
			get
			{
				return this._add_datetime;
			}
			set
			{
				if ((this._add_datetime != value))
				{
					this._add_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_datetime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime update_datetime
		{
			get
			{
				return this._update_datetime;
			}
			set
			{
				if ((this._update_datetime != value))
				{
					this._update_datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_add", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string user_add
		{
			get
			{
				return this._user_add;
			}
			set
			{
				if ((this._user_add != value))
				{
					this._user_add = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_update", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string user_update
		{
			get
			{
				return this._user_update;
			}
			set
			{
				if ((this._user_update != value))
				{
					this._user_update = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_log_interface")]
	public partial class order_log_interface : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _method;
		
		private string _api_function;
		
		private string _api_data_header;
		
		private string _api_data_detail;
		
		private string _ip_address;
		
		private System.DateTime _create_date;
		
		private EntitySet<order_transaction> _order_transactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnmethodChanging(string value);
    partial void OnmethodChanged();
    partial void Onapi_functionChanging(string value);
    partial void Onapi_functionChanged();
    partial void Onapi_data_headerChanging(string value);
    partial void Onapi_data_headerChanged();
    partial void Onapi_data_detailChanging(string value);
    partial void Onapi_data_detailChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    #endregion
		
		public order_log_interface()
		{
			this._order_transactions = new EntitySet<order_transaction>(new Action<order_transaction>(this.attach_order_transactions), new Action<order_transaction>(this.detach_order_transactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_method", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string method
		{
			get
			{
				return this._method;
			}
			set
			{
				if ((this._method != value))
				{
					this.OnmethodChanging(value);
					this.SendPropertyChanging();
					this._method = value;
					this.SendPropertyChanged("method");
					this.OnmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_api_function", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string api_function
		{
			get
			{
				return this._api_function;
			}
			set
			{
				if ((this._api_function != value))
				{
					this.Onapi_functionChanging(value);
					this.SendPropertyChanging();
					this._api_function = value;
					this.SendPropertyChanged("api_function");
					this.Onapi_functionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_api_data_header", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string api_data_header
		{
			get
			{
				return this._api_data_header;
			}
			set
			{
				if ((this._api_data_header != value))
				{
					this.Onapi_data_headerChanging(value);
					this.SendPropertyChanging();
					this._api_data_header = value;
					this.SendPropertyChanged("api_data_header");
					this.Onapi_data_headerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_api_data_detail", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string api_data_detail
		{
			get
			{
				return this._api_data_detail;
			}
			set
			{
				if ((this._api_data_detail != value))
				{
					this.Onapi_data_detailChanging(value);
					this.SendPropertyChanging();
					this._api_data_detail = value;
					this.SendPropertyChanged("api_data_detail");
					this.Onapi_data_detailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_log_interface_order_transaction", Storage="_order_transactions", ThisKey="id", OtherKey="log_id")]
		public EntitySet<order_transaction> order_transactions
		{
			get
			{
				return this._order_transactions;
			}
			set
			{
				this._order_transactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_order_transactions(order_transaction entity)
		{
			this.SendPropertyChanging();
			entity.order_log_interface = this;
		}
		
		private void detach_order_transactions(order_transaction entity)
		{
			this.SendPropertyChanging();
			entity.order_log_interface = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_session")]
	public partial class order_session : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Guid _session_guid;
		
		private string _sale_order_no;
		
		private string _sale_order_status;
		
		private string _sale_platform;
		
		private string _pos_order_no;
		
		private string _pos_order_status;
		
		private System.DateTime _create_date;
		
		private System.Nullable<System.DateTime> _modified_date;
		
		private EntitySet<order_transaction> _order_transactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onsession_guidChanging(System.Guid value);
    partial void Onsession_guidChanged();
    partial void Onsale_order_noChanging(string value);
    partial void Onsale_order_noChanged();
    partial void Onsale_order_statusChanging(string value);
    partial void Onsale_order_statusChanged();
    partial void Onsale_platformChanging(string value);
    partial void Onsale_platformChanged();
    partial void Onpos_order_noChanging(string value);
    partial void Onpos_order_noChanged();
    partial void Onpos_order_statusChanging(string value);
    partial void Onpos_order_statusChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    partial void Onmodified_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_dateChanged();
    #endregion
		
		public order_session()
		{
			this._order_transactions = new EntitySet<order_transaction>(new Action<order_transaction>(this.attach_order_transactions), new Action<order_transaction>(this.detach_order_transactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid session_guid
		{
			get
			{
				return this._session_guid;
			}
			set
			{
				if ((this._session_guid != value))
				{
					this.Onsession_guidChanging(value);
					this.SendPropertyChanging();
					this._session_guid = value;
					this.SendPropertyChanged("session_guid");
					this.Onsession_guidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale_order_no", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sale_order_no
		{
			get
			{
				return this._sale_order_no;
			}
			set
			{
				if ((this._sale_order_no != value))
				{
					this.Onsale_order_noChanging(value);
					this.SendPropertyChanging();
					this._sale_order_no = value;
					this.SendPropertyChanged("sale_order_no");
					this.Onsale_order_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale_order_status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sale_order_status
		{
			get
			{
				return this._sale_order_status;
			}
			set
			{
				if ((this._sale_order_status != value))
				{
					this.Onsale_order_statusChanging(value);
					this.SendPropertyChanging();
					this._sale_order_status = value;
					this.SendPropertyChanged("sale_order_status");
					this.Onsale_order_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale_platform", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sale_platform
		{
			get
			{
				return this._sale_platform;
			}
			set
			{
				if ((this._sale_platform != value))
				{
					this.Onsale_platformChanging(value);
					this.SendPropertyChanging();
					this._sale_platform = value;
					this.SendPropertyChanged("sale_platform");
					this.Onsale_platformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos_order_no", DbType="NVarChar(50)")]
		public string pos_order_no
		{
			get
			{
				return this._pos_order_no;
			}
			set
			{
				if ((this._pos_order_no != value))
				{
					this.Onpos_order_noChanging(value);
					this.SendPropertyChanging();
					this._pos_order_no = value;
					this.SendPropertyChanged("pos_order_no");
					this.Onpos_order_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos_order_status", DbType="Char(10)")]
		public string pos_order_status
		{
			get
			{
				return this._pos_order_status;
			}
			set
			{
				if ((this._pos_order_status != value))
				{
					this.Onpos_order_statusChanging(value);
					this.SendPropertyChanging();
					this._pos_order_status = value;
					this.SendPropertyChanged("pos_order_status");
					this.Onpos_order_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_date
		{
			get
			{
				return this._modified_date;
			}
			set
			{
				if ((this._modified_date != value))
				{
					this.Onmodified_dateChanging(value);
					this.SendPropertyChanging();
					this._modified_date = value;
					this.SendPropertyChanged("modified_date");
					this.Onmodified_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_session_order_transaction", Storage="_order_transactions", ThisKey="id", OtherKey="session_id")]
		public EntitySet<order_transaction> order_transactions
		{
			get
			{
				return this._order_transactions;
			}
			set
			{
				this._order_transactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_order_transactions(order_transaction entity)
		{
			this.SendPropertyChanging();
			entity.order_session = this;
		}
		
		private void detach_order_transactions(order_transaction entity)
		{
			this.SendPropertyChanging();
			entity.order_session = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_transaction")]
	public partial class order_transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _session_id;
		
		private long _log_id;
		
		private string _datail;
		
		private System.DateTime _create_date;
		
		private EntityRef<order_log_interface> _order_log_interface;
		
		private EntityRef<order_session> _order_session;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onsession_idChanging(long value);
    partial void Onsession_idChanged();
    partial void Onlog_idChanging(long value);
    partial void Onlog_idChanged();
    partial void OndatailChanging(string value);
    partial void OndatailChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    #endregion
		
		public order_transaction()
		{
			this._order_log_interface = default(EntityRef<order_log_interface>);
			this._order_session = default(EntityRef<order_session>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_id", DbType="BigInt NOT NULL")]
		public long session_id
		{
			get
			{
				return this._session_id;
			}
			set
			{
				if ((this._session_id != value))
				{
					if (this._order_session.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsession_idChanging(value);
					this.SendPropertyChanging();
					this._session_id = value;
					this.SendPropertyChanged("session_id");
					this.Onsession_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", DbType="BigInt NOT NULL")]
		public long log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					if (this._order_log_interface.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datail", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string datail
		{
			get
			{
				return this._datail;
			}
			set
			{
				if ((this._datail != value))
				{
					this.OndatailChanging(value);
					this.SendPropertyChanging();
					this._datail = value;
					this.SendPropertyChanged("datail");
					this.OndatailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_log_interface_order_transaction", Storage="_order_log_interface", ThisKey="log_id", OtherKey="id", IsForeignKey=true)]
		public order_log_interface order_log_interface
		{
			get
			{
				return this._order_log_interface.Entity;
			}
			set
			{
				order_log_interface previousValue = this._order_log_interface.Entity;
				if (((previousValue != value) 
							|| (this._order_log_interface.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order_log_interface.Entity = null;
						previousValue.order_transactions.Remove(this);
					}
					this._order_log_interface.Entity = value;
					if ((value != null))
					{
						value.order_transactions.Add(this);
						this._log_id = value.id;
					}
					else
					{
						this._log_id = default(long);
					}
					this.SendPropertyChanged("order_log_interface");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_session_order_transaction", Storage="_order_session", ThisKey="session_id", OtherKey="id", IsForeignKey=true)]
		public order_session order_session
		{
			get
			{
				return this._order_session.Entity;
			}
			set
			{
				order_session previousValue = this._order_session.Entity;
				if (((previousValue != value) 
							|| (this._order_session.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order_session.Entity = null;
						previousValue.order_transactions.Remove(this);
					}
					this._order_session.Entity = value;
					if ((value != null))
					{
						value.order_transactions.Add(this);
						this._session_id = value.id;
					}
					else
					{
						this._session_id = default(long);
					}
					this.SendPropertyChanged("order_session");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
